# # Stage 1: Build React App
# FROM node:22 AS builderFE
# WORKDIR /app1
# COPY package.json yarn.lock ./
# RUN yarn install
# COPY . .
# RUN yarn build

# # Stage 2: Nginx để chạy React App
# FROM nginx:alpine
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=builderFE /app1/build /usr/share/nginx/html


# Stage 1: build Next.js
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

# Stage 2: production image
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./
ENV NODE_ENV=production
EXPOSE 3000
CMD ["yarn", "start"]

