version: '3.4'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user_manager
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - db


  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgres  # Tên service = hostname
      - DB_PORT=5432
      - DB_NAME=user_manager
      - DB_USER=root
      - DB_PASSWORD=1234
    expose:
      - 8000
    depends_on:
      - postgres

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - db
  #   depends_on:
  #     - backend

networks:
  db:
    driver: bridge

volumes:
  postgres_data:
